package com.carpoint.boxscanner.main;

public class T {
    public static final String
            tagIdPlan = "id_plan",
            tagIdQuestion = "id_question",
            tagIdGroup = "id_group",
            tagPlans = "plans",
            tagLogin = "LOGIN",
            tagControler = "is_controller",
            tagName = "name",
            tagDrawDate = "draw_date",
            tagError = "ERROR",
            tagErrors = "errors",
            tagQuestionsGroups = "questions_groups",
            tagSerial = "serial",
            tagFullname = "fullname",
            tagAnswers = "answers",
            tagAnswers2 = "answers2",
            tagAnswer = "answer",
            tagLastQ = "last_question",
            tagQuestions = "questions",
            tagType = "type",
            tagIdError = "id_error",
            tagCmnError = "common_id_errors",
            tagYesNo = "yesno",
            tagYes = "yes",
            tagPhoto = "photo",
            tagText = "text",
            tagNumber = "number",
            tagNumberYes = "numberyes",
            tagPhotoReq = "photo_required",
            tagResolvedBy = "resolved_by",
            tagResolvedTime = "resolved_time",
            tagIdPhotoSign = "id_photo_sign",
            tagVirtualText = "virtual_text",
            tagManualText = "manual_text",
            tagPhotoText = "photo_text",
            tagErrorList = "errorList",
            tagChecked = "checked",
            tagPrErrID = "id_pr_err",
            tagIdProtocol = "id_protocol",
            tagNull = "null",
            tagPositiveAnswer = "1",
            tagNegativeAnswer = "0",
            tagNaAnswer = "-1",
            tagLocLat = "loc_lat",
            tagLocLng = "loc_lng",
            tagLimitPlus = "limit_plus",
            tagLimitMinus = "limit_minus",
            tagIdLastProto = "id_last_protocol",
            tagVirtual = "is_virtual",
            tagManual = "manual_text",
            tagNone = "",
            tagUncomplete = "uncomplete",
            MIME_TEXT_PLAIN = "text/plain",
            tagCreatedBy = "created_by",
            tagOnlyController = "only_controller",
            tagIsUniversal = "is_universal";

}
